apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-logging
  namespace: monitoring
  labels:
    k8s-app: kibana-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-logging
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
    spec:
      containers:
      - name: kibana-logging
        image: barasher/kibana-arm:7.10.0
        env:
          - name: ELASTICSEARCH_URL
            value: 192.168.3.10:9200
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: monitoring
  labels:
    k8s-app: kibana-logging
    kubernetes.io/name: "Kibana"
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 5601
    protocol: TCP
    targetPort: ui
  loadBalancerIP: 192.168.3.204
  selector:
    k8s-app: kibana-logging