---

- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: preflight
    - role: download

- hosts: master
  become: yes
  roles:
    - role: k3s/master
    - role: helm

- hosts: node
  become: yes
  roles:
    - role: k3s/node

- hosts: all
  become: yes
  roles:
    - role: k3s/all