---

- name: "Create dev group"
  group:
    name: "dev"
    state: present

- name: "Create user accounts and add users to dev group"
  user:
    name: "{{ item }}"
    state: present
    shell: /bin/bash
    groups: "dev"
  with_items: "{{ users }}"

- name: "Create SSH Keys for each account"
  community.crypto.openssh_keypair:
    path: ~/.ssh/{{ item }}.key
  with_items: "{{ users }}"

- name: "Add authorized keys"
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', '~/.ssh/'+ item + '.key.pub') }}"
  with_items: "{{ users }}"