---

- name: Install iptables
  ansible.builtin.apt:
    name: iptables
    state: present

- name: Set KUBECONFIG /etc/environment 
  ansible.builtin.lineinfile:
    path: /etc/environment'
    line: 'KUBECONFIG=/etc/rancher/k3s/k3s.yaml'
  ignore_errors: true