apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glance
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cfkoehler/pi-k3-install.git
    targetRevision: main
    path: argo/glance
    helm:
      releaseName: glance
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
