---

- name: Add longhorn helm repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
  run_once: true

- name: Install longhorn
  shell: helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace --version 1.2.4
  run_once: true
  ignore_errors: true

- name: Install longhorn Service
  shell: kubectl apply -f ~/pi-k3-install/k3s-configs/longhorn/service.yaml
  run_once: true

# - name: Set Longhorn as default storage
#   shell: kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
#   run_once: true