---

- name: Remove Docker for clean slate
  ansible.builtin.apt:
    pkg:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - rnc
    state: absent

- name: Install Docker prerequisites
  ansible.builtin.apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    state: present

- name: Create GPG key directory
  file:
    path: /etc/api/keyrings
    state: directory
    owner: root
    group: root

- name: Install GPG key
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

- name: Install Docker Repository
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Run apt-get
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker
  ansible.builtin.apt:
    pkg:
    - docker
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
    state: present

- name: Copy Docker Daemon
  template:
    src: "daemon.json"
    dest: "/etc/docker/daemon.json"
    owner: root
    group: root
    mode: 0644
    force: false

- name: Enable and check Docker service
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes